### ISSUE TITLE
Implementation question: why not use dot+space

### ISSUE THREAD

**Issue by apc** [jeeger/twauctex#1]
Thanks for this. I'm new to Emacs and trying to replicate a similar system I had setup in my previous editor. 

Is there a reason not to use ". " instead of "." as the 'trigger"? I gather that would require making the SPC electric instead of ".". But it would get around having to have a list of expressions where you want no space after the period and it would also allow you to be able to type e.g. `p.~23', where you do want a nonbreaking space after the period. 

I ask in case you thought about doing this way and found a reason against this. If not, I'll try and tweak things on my end and see if I can make it work the way I'm suggesting. (I'm thinking one of abo-abo's suggestions [here](https://stackoverflow.com/questions/17865975/emacs-abbreving-to-ending-sentence) might work...)

**Comment by jeeger** [comment]
While this approach would mitigate the line breaking for abbreviation *internal* periods (like the first period in `e.g.`), the final dot would still require special handling using the abbreviation finding code.
You'll definitely want to write something like 
```
There are such things (e.g. ducks).
```
without a line break after the period after the `g`. I don't think we can remove the abbreviation handling code.

Additionally, writing something like 
```
See p.~23
```
is handled in my code by double-pressing the dot, which deletes the added newline (this should be in the documentation). It would be simpler to not have to double-press the dot, however.

So implementing an electric space would slightly simplify the abbreviation-detection code, and make writing dots without spaces a bit easier.

Since space is electric anyways for the inter-sentence and inter-word spacing anyways, feel free to try out an electric space.

My approach for one-sentence-per-line would be:
- Electric space function looks back if a `twauctex-electric-char` is the last character
- If yes, check for abbreviations.
- If abbreviation, insert inter-word-spacing (`\ `)
- If not abbreviation, insert newline.

Other things that could be slightly simplified:
- `twauctex--update-abbrev-regexp` could lose the splitting on internel dots
- Inter-sentence and inter-word spacing could be merged.

So yes, I'd be very interested in having a look at this approach (even just the preliminary implementation, I can do the bells and whistles myself).

**Comment by apc** [comment]
I see. That makes sense. I was thinking one could take advantage of emacs own `sentence-end` to deal with, say, sentences ending in parentheses. This is far from a sophisticated solution, but here's what I currently have based on some suggestions on SE. 

```
(defun electric-space () ; Trying to get Emacs to do semantic linefeeds
  (interactive)
  (if (looking-back (sentence-end))
      (insert " %\n")
    (self-insert-command 1))
  )
  (defvar electric-space-on-p t)
  (defun toggle-electric-space ()
    (interactive)
    (global-set-key
     " "
     (if (setq electric-space-on-p
               (not electric-space-on-p))
         'electric-space
       'self-insert-command)))
```

At the moment I have to manually add `~` after `e.g.`, `i.e.`, `cf.` etc. I've read somewhere that this is supposed to be good practice anyway, so that a space after a period in `tex` is reserved for end of sentences. I don't know whether that's true, nor whether it matters if it is. 

I'll try to play around with your suggestions above. I'm pretty new to this whole world, so it may take a while.

**Comment by jeeger** [comment]
Unfortunately, the `sentence-end` regex isn't smart enough to work on something like this:
```
He is a PhD. |who likes to work.
```
At the `|`, it matches, even though it's not a sentence end.

We *could* leave out abbreviation detection completely, but I really want to make this code as smart as possible so you can write as you normally would, with a minimum of extra keystrokes.

I've not seen the recommendation to put non-breaking spaces after abbreviations anywhere yet, which is why I implemented the abbreviation detection (which is also used in the fill function).

**Comment by apc** [comment]
Maybe I'm misremembering. Perhaps the recommendation is just to not use a period followed after a space unless the period marks the end of a sentence? If so, then using SPC as the trigger could still make sense, since you'd write instead `p.~`, `e.g.\ `, etc. But yes, I like your original system which takes care of stuff like that automatically. 

Why are you thinking one would need to use something like `|` in such a setting? Is there a specific scenario you have in mind? (Perhaps using `\verb`?)

A different question: how would you tweak your package so that one can type `.)`? I gather making `!` and `?` electric would be one way to allow for sentences ending with something other than a period (and redefining `\ldots`, say, for sentences ending with ellipses would be a way to deal with, well, `\ldots`).

**Comment by jeeger** [comment]
Hello!
I was just using the pipe to illustrate the position where `(looking-at (sentence-end))` returns true, even if it's not at the end of the sentence.

You *can* type something like 
```
I need to visit the supermarket (do I really?).
```

and supress the line break at the question mark by double-tapping it. So far, I've had very few instances of having punctuation in parentheses.

**Comment by apc** [comment]
Got it. I keep thinking space followed by a period is a more reliable indicator of the end of a sentence than a single period, though perhaps I'm wrong. And even if I'm not, perhaps managing the exceptions going one way is easier than managing them using the others. When using ST3, I just had a regexp that would look back and insert a new line after `.`-`SPC` if the string preceding `.` wasn't among a list of exceptions. I see that your approach is quite similar, and perhaps the difference isn't worth the trouble. I'll still see if I can fiddle with this and will let you know if I come up with something that seems promising.

**Comment by jeeger** [comment]
Yes, I'd be grateful if you could submit a very simple proof-of-concept implementation, I'd be perfectly willing to patch it up with the "abbreviation" mechanism and the other features.

**Comment by jeeger** [comment]
I've implement this in the `electric-space` branch. I'll use it for a few days and see how it works.

**Comment by apc** [comment]
Nice! Sorry for the delay: busy couple of weeks here. I'll play around with this next week.

**Comment by jeeger** [comment]
Hey, no problem at all, it was about an hour of work! It seems to work much better, I'll see whether I can find any bugs and then merge it into the main branch.

**Comment by apc** [comment]
Good to hear! I've been enjoying this so far. Thanks!

I've been trying to figure out how to extend the functionality so that `.)` also triggers a new line (and ditto for `?)` and `!)`. I tried changing `twauctex-electric-chars` to include what I thought would be the right regexp---I figured I also needed to change the `:type` value from `character` to `string`---but that didn't work. Ultimately I came to suspect that the problem comes from the way the value of `twauctex-electric-chars` is used by `twauctex--update-electric-regexp`. I still didn't manage to get it to work, though, so any hints would be most helpful. 

Finally, I don't know if this is the intended behavior: if I type a single letter followed by a period and a space *outside*  of the `document` environment, I get an error message: 

```
looking-back: Invalid search bound (wrong side of point) [8 times]
```

**Comment by jeeger** [comment]
Thanks for using it! Yeah, `twauctex-electric-chars` is a list of characters, not a list of regexes. Icould rework this into regexes, and it should not be a big change. 

Could you open two issues for this (one "enhancement" for the regexes, one "bug" for the invalid search bound)? I'll close this issue then.

Edit: Can't really reproduce the search-bound error here, we can hash it out in the other issue.

**Comment by jeeger** [comment]
This is now done, barring more bugs. I'll merge this into main soonish.
