### ISSUE TITLE
Remove visual-fill-column-mode dependency?

### ISSUE THREAD

**Issue by apc** [jeeger/twauctex#6]
Is there a reason not to at least have an option to prevent adding `visual-fill-column-mode` to `hack-local-variables-hook`? I'm a happy user of `olivetti-mode`, for example, and `visual-fill-column-mode` it doesn't play well with it. (I also prefer not to use `visual-fill-column-mode` since it messes with my modeline configuration.) Even if you'd want `visual-fill-column-mode` to be called by default, It seems like it wouldn't be difficult to just have a boolean that would allow a user to change the default.

**Comment by jeeger** [comment]
That makes sense. I'll make it conditional, since using OSPL without some sort of visual line breaking mode makes it look pretty horrible.

**Comment by jeeger** [comment]
You can try it out by setting `twauctex-use-visual-fill-column` to `nil` and restarting emacs. Also thanks for pointing me to olivetti-mode, I've been looking for horizontal text centering for some time now.

**Comment by xiangsheng** [comment]
Setting `twauctex-use-visual-fill-column` to `nil` really helps me out of some weird situation recently. But I still don't why it is necessary to add `visual-fill-column-mode` to `hack-local-variables-hook`, which has a global side effect even outside the buffer where `twauctex mode` is enabled. 

In fact, after updating to emacs 28, I notice that the `visual-fill-column` mode is turned on for every newly opened buffer. After some investigation, I found this is caused by `twauctex mode`. It is quite strange that this thing only happens in emacs 28 since I've never noticed similar things in emacs 27 with the same settings.
